M48
; DRILL file {KiCad 7.0.7} date Mon Sep 25 17:24:55 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-25T17:24:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.5594Y0.2728
X0.787Y0.2728
T2
X0.1378Y1.2126
X1.2087Y2.2874
X1.2087Y0.1378
T0
M30
